#!/bin/bash
source helper

docker run --dns 192.168.1.179 -e DATABASE_SOURCE="postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable" -v /var/run/docker.sock:/run/docker.sock --rm -v `pwd`:/docker -w /docker -it ${IMAGE} bash
